### ISSUE TITLE
OutofMemoryError: Java heap space

### ISSUE THREAD

**Issue by natetoombs** [sparkfun/SparkFun_MLX90640_Arduino_Example#14]
I'm trying to run the Example2_OutputToProcessing sketch for an extended period of time, but after a few hours, I run into an OutofMemoryError with the Java heap space. Does anyone know how I can fix this to allow the program to run indefinitely? I have no experience with Java, any help is appreciated!!!

**Comment by santaimpersonator** [comment]
I don't see a point where there would be memory leakage from the example code. This sounds more like an issue with the Processing IDE.

No other users report same issue; closing issue for now.
