### ISSUE TITLE
NaN result for specific pixel

### ISSUE THREAD

**Issue by vishalkothari** [sparkfun/SparkFun_MLX90640_Arduino_Example#16]
Hi,

I am running Example2_OutputToProcessing.
I am facing a problem that Pixel 22 always has value NaN. All other pixel values seem to be ok. 
I traced this further and found that irData calculated in MLX90640_API.cpp > MLX90640_CalculateTo() has a large negative value like -6874.43 for Pixel 22. irData for other pixels is in -10 to -20 range.

I have tested this with Teensy 3.5 and ESP32, I see the same issue with both.
Has anyone faced similar issue?

**Comment by LBuydens** [comment]
Hi, 

the MLX90640 can have up to 4 dead pixels.  These should be indicated in the EEPROM table.  I expect that in your sensor, pixel 22 is malfunctioning.  Depending on your application you can ignore that pixel or replace it by the median temperature value of the surrounding pxiels.

**Comment by vishalkothari** [comment]
Thanks @LBuydens .
