### ISSUE TITLE
'Serial' was not declared in this scope

### ISSUE THREAD

**Issue by h-Naima-s** [sparkfun/SparkFun_MLX90640_Arduino_Example#18]
Getting the following error message when uploading this code on arduino:

sketch\MLX90640_I2C_Driver.cpp: In function 'int MLX90640_I2CRead(uint8_t, unsigned int, unsigned int, uint16_t*)':

MLX90640_I2C_Driver.cpp:48:7: error: 'Serial' was not declared in this scope

       Serial.println("No ack read");

       ^

sketch\MLX90640_I2C_Driver.cpp: In function 'int MLX90640_I2CWrite(uint8_t, unsigned int, uint16_t)':

MLX90640_I2C_Driver.cpp:95:5: error: 'Serial' was not declared in this scope

     Serial.println("Error: Sensor did not ack");

     ^

exit status 1
'Serial' was not declared in this scope

**Comment by qTp** [comment]
Has a solution been found for this problem?
I get the same error message, with an Adruino Leonardo board.

**Comment by h-Naima-s** [comment]
Yes! so you need to run the code as it is on Processing app. It will show you 2 ports with error message, and out of those 2 will show you one as available. you need to then go to myPort on line 59 and change the port number to one that is showing available. 
This was what going wrong with me.

**Comment by qTp** [comment]
thanks for the fast answer. 
i've found another soultion:
       In the MLX90640_I2C_Driver.h, i included the "Arduino.h" header file.

**Comment by santaimpersonator** [comment]
Seems resolved and Arduino header previously mentioned in issue #2.

Closing issue.
