### ISSUE TITLE
MLX90640 not detected after couple of minutes

### ISSUE THREAD

**Issue by sebmorales** [sparkfun/SparkFun_MLX90640_Arduino_Example#3]
Hi, 
Not sure what is going on, or if this is a problem with the library. I tied the code and connected to the processing sketch and it worked great for a couple of minutes. Then it gave me an error saying no ack read. After reseting the error change to:"MLX90640 not detected at default I2C addres. Please check wiring. Freezing."

The sensor started working again after a couple minutes but the same thing happened then. This repeated for a handful of times. Works for a couple of minutes then I2C freezes. 

Now the sensor won't start at all.

I am using Qwiic IR Array MLX90640 with a teensy 3.5. Nothing else just sample code.  

Any ideas of what I might try?
Thanks

**Comment by nseidle** [comment]
Oiy. I'm not sure what that could be. I'm going to lean towards sensor failure and not lib failure.

One way to check: do some low level I2C reads of the sensor. Or just run the [I2C scanner ](https://playground.arduino.cc/Main/I2cScanner) to see if the sensor even responds to I2C queries.

**Comment by sebmorales** [comment]
I tied it again yesterday and it was working with no problems... Not sure if something was causing too much noise for the i2c communication...

**Comment by nseidle** [comment]
Hmm, finicky hardware issue. Double check the solder connections on our board. If they look solid (they should) then I have to begin to point at the MLX90640 sensor itself. I have not experience this before. Please check back in and let us know what you find!

**Comment by sebmorales** [comment]
The solders looked good and I reflowed them just to make sure. I still have the same problem. Sometimes it works well, then will stop for a while then start working again, stopping suddenly.

"MLX90640 not detected at default I2C addres. Please check wiring. Freezing."

**Comment by nseidle** [comment]
I assume you're powering it at 3.3V?

**Comment by sebmorales** [comment]
Yes, I am connecting to the following pins: 
![teensy3 5pins](https://user-images.githubusercontent.com/12665779/42358119-09e233fe-80a9-11e8-9d6e-6aec416f67cb.jpg)

**Comment by nseidle** [comment]
That's our setup as well. It's sounding like a bad sensor. Please contact [SparkFun tech support](https://www.sparkfun.com/technical_assistance) and reference this discussion. They should be able to get you a replacement sensor. We may need the defective sensor back so that we can work with Melexis to figure out what's going on.

**Comment by tsb4** [comment]
I had the same problem here, with an ESP32. Did you get solved the problem?
