### ISSUE TITLE
License file missing

### ISSUE THREAD

**Issue by FredrikWendt** [sparkfun/SparkFun_MLX90640_Arduino_Example#5]
> Please review the LICENSE.md file for license information.

Uhm, which file? I think you forgot to include the actual LICENSE.md file :-)

**Comment by nseidle** [comment]
(scrounges through box until finding a license file...)

Oh, you mean [this one](https://github.com/sparkfun/SparkFun_MLX90640_Arduino_Example/blob/master/LICENSE.md)? Right! Sorry, I forgot to include it. We're very open source so feel free to do whatever you want with our code. If something is not clear in the license please let me know and I'll correct it.
