### ISSUE TITLE
Synchronizing two sensors

### ISSUE THREAD

**Issue by kozuch** [sparkfun/SparkFun_MLX90640_Arduino_Example#8]
Is it possible to frame-synchronize two MLX90640 sensors so that they take a reading (image) exactly at the same time? Is it possible to have a synchronized "video stream" from two sensors where the individual frames are in sync?

**Comment by nseidle** [comment]
A very interesting question. I don't know of a good way to sync two sensors. The MLX90640 does not have an interrupt pin so to sync 2 sensors you'd need a high speed processor to poll the devices simultaneously (or nearly so) and then stitch the frames together. Tricky, but it may be possible.

Sorry I don't have a better solution for you!
